export {default as Navbar} from './navbar/Navbar'
export {default as Hero} from './hero/Hero'
export {default as Services} from './services/Services'
export {default as Card} from './card/Card'
export {default as Footer} from './footer/Footer'